---
swagger: "2.0"
info:
  description: __rootArtifactId__ REST API definition
  version: 1.0.0
  title: __rootArtifactId__
basePath: /api
schemes:
- http

tags:
- name: Entity1
  description: The Entity1 resource, accessed by its ID

paths:
  /entity1:
    get:
      tags:
      - Entity1
      description: Retrieves a list of the resource Entity1 filtered by query string.
      operationId: findEntity1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: filter
        type: string
        required: false
        description: The filter criteria for retrieving the list
      - in: query
        name: startIndex
        type: integer
        format: int32
        required: false
        description: The start index of the first element to return (page start)
      - in: query
        name: pageSize
        type: integer
        format: int32
        required: false
        description: Maximum number of items to return in requested page.  If the list is exausted, less elements will be returned.
      responses:
        200:
          description: requested page of items matching criteria.
          schema:
            type: array
            items:
              $ref: "#/definitions/Entity1"

    post:
      tags:
      - Entity1
      description: Insert a new instance of the resource Entity1.
      operationId: createEntity1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: entity1
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/Entity1"
      responses:
        201:
          description: Created Entity1 resource.
          schema:
            $ref: "#/definitions/Entity1"
        409:
          description: Entity with same ID already exists.
              
  /entity1/{id}:
    get:
      tags:
      - Entity1
      description: Retrieves an instance of the resource Entity1, having the specified id.
      operationId: getEntity1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the requested Entity1 instance
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful response, with a representation of the Entity1 resource.
          schema:
            $ref: "#/definitions/Entity1"
          examples:
            application/json :
              {
                id : 1234,
                name : Weekly
              }
        404:
          description: The requested Entity1 resource instance was not found.

    post:
      tags:
      - Entity1
      description: Updates an existing instance of the resource Entity1, having the specified id.
      operationId: updateEntity1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the Entity1 instance to be updated
        required: true
        type: integer
        format: int64
      - in: body
        name: entity1
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/Entity1"
      responses:
        200:
          description: Successful response, with a representation of the Entity1 resource.
          schema:
            $ref: "#/definitions/Entity1"
        404:
          description: The requested Entity1 resource instance was not found.
     
definitions:
  Entity1:
    type: object
    description: An individual Entity1 resource instance.
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
