---
# This is a shopping list API.  
swagger: "2.0"
info:
  description: Microservice1 REST API definition
  version: 1.0.0
  title: Microservice1
basePath: /api
schemes:
- http

# Tags organize operations into groups for presentation in the Swagger UI.
# Each tag has an optional description, which the Swagger UI will display in 
# the tag group header.
tags:
- name: Entity1
  description: The Entity1 resource, accessed by its ID

paths:

  # Each Path Item Object describes a resource, containing a set of operations
  # at a specified path.  The Path Item object can define parameters and 
  # responses common all of its contained operations.
  /entity1/{id}:

    # Operations are identified by an HTTP method.  
    get:
      tags:
      - Entity1
      description: Retrieves an instance of the resource Entity1, having the specified id.
      operationId: getEntity1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the requested Entity1 instance
        required: true
        type: string
      responses:
        200:
          description: Successful response, with a representation of the Entity1 resource.
          schema:
            # Reference to a Schema Object described in 'definitions' section
            $ref: "#/definitions/Entity1"
          examples:
            # Example message, keyed by media type
            application/json :
              {
                id : 1234,
                name : Weekly
              }
        404:
          description: The requested Entity1 resource instance was not found.
 
# The definitions section contains a set of named Schema Objects.  Each schema
# object describes a reusable data type, which can be reference by name.
definitions:
  Entity1:
    type: object
    description: An individual Entity1 resource instance.
    properties:
      id:
        type: string
      name:
        type: string
